[package]
name = "koules-rs"
version = "0.1.0"
license = "GPL-3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bevy_prototype_lyon = "0.4.0"
bevy_mouse_tracking_plugin = "0.2.0"
